CloudHub:  
  Env: "DEV"
  Orgid: "MuleSoft"
  Applications:
    -
      name: "maven-project-ir-ecotricity"
      version: "1.0.0-SNAPSHOT.zip"
      worker-size: "0.1"
      num-of-workers: "1"
      runtime: "3.8.5"
      region: "eu-west-1"
      properties: "maven-project-ir-ecotricity-dev.properties"
      repo_endpoint: 'https://github.com/igor-repka/packages/raw/master/'
      filename: "maven-project-ir-1.0.0-SNAPSHOT.zip"
    -
      name: "bid-processing-ir-ecotricity"
      version: "1.0.0-SNAPSHOT.zip"
      worker-size: "1"
      num-of-workers: "1"
      runtime: "3.8.5"
      region: "eu-west-1"
      properties: "bid-processing-ir-ecotricity-dev2.properties"
      repo_endpoint: 'https://github.com/igor-repka/packages/raw/master/'
      filename: "bid-processing-1.0.0-SNAPSHOT.zip"

