CloudHub:
  Env: "Sandbox"
  BusinessGroup: "MuleSoft"
  Applications:
    -

OnPrem:
  Env: "DEV"
  BusinessGroup: "MuleSoft"
  Applications:
    -
      name: "cicd_buil_hello_world"
      packageName: "hello-world-api-1.0.4.zip"
      properties: "hello-world-api-v1-dev.properties"
      repo_endpoint: 'http://localhost:8888/repository/maven-releases/com/mule/deploy/test/hello-world-api/1.0.4/'
      target: snow_3_9_0
