version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - run: echo "hello world"
  deployment:
    production: # just a label; label names are completely up to you
      branch: master
      commands:
        #- ./deploy-to-production.sh
        - echo "deployment prod"
