version: 2
jobs:
   build:
     docker:
       - image: circleci/openjdk:8
     steps:
       - checkout
       - run: echo "hello world"
   deployment:
      production:
        branch: master
        commands:
          - ./deployment.sh
      staging:
        branch: master
        commands:
          - ./deployment.sh